import React from 'react';
import './../assets/css/privacy.css';
import {Link} from 'react-router-dom';



export default class Privacy extends React.Component{

  render(){

    return(
    <>
    <div class="content">
    <h2 style={{textAlign:'center'}}>Binco Privacy Policy</h2><br/>
    <p>Thank you for your interest in our website. In the following, we will inform you in detail about the processing of personal data when using this website. Personal data means all data that can be personally related to you, e.g. name, address, telephone number, email address or user behavior.</p>
    <h3>1. Who is responsible for data processing?</h3>
    <p>The service provider and party responsible for processing personal data (“controller”) is Binco, Inc., 1572 Roseytown Road, Greensburg, PA 15601 (“Binco”).</p>
    <p>If you have any questions about the collection, processing, or usage of data; if you have requests for information, correction, disabling or deletion of data; or if you want to revoke a previously given consent; or if you want to object to the usage of your information for advertising purposes, please use the settings provided in your account’s user area, or else contact us at one of the following addresses:</p>
    <p>Email: info@binco.com</p>
    <p>Fax: 123123</p>
    <h3>2. To what extent is personal data processed?</h3>
    <h3>2.1 Collection of personal data when you visit our website</h3>
    <h4>a) Log files</h4>
    <p>If you visit our site for informational purposes but don’t register with us, create an account, order something, or otherwise deliberately transfer information to us, we collect information from your browser to help us serve our websites to you. In particular, we collect </p>
    <ul>
      <li>IP address,</li>
      <li>date and time of the request,</li>
      <li>time zone difference to Greenwich Mean Time (GMT),</li>
      <li>name of the requested file,</li>
      <li>access status/HTTP status code,</li>
      <li>volume of data transferred,</li>
      <li>the page from which you came to visit us,</li>
      <li>your operating system and its interface,</li>
      <li>your browser type and the language and version of the browser software,</li>
      <li>a report of successful retrieval</li>
      <p>The data is technically necessary for us to display our website to you. It is also evaluated to make the website user-friendly and to ensure stability and security. For this purpose, we partly use the external web hosting service providers Akamai Technologies, Inc. and Amazon Web Services, Inc.</p>
    </ul>
    <h4>b) Cookies and similar technologies</h4>
    <p>We also use “cookies” on our sites. Cookies are small text files that are assigned to your browser and stored on your device. Through them, certain information flows to the place that sets the cookie, such as settings or data for exchange with the system. This helps us to make our website more user-friendly and effective overall. The legal bases for this are your consent and our legitimate interests. Cookies cannot execute programs or transmit viruses to your device. </p>
    <p>We use session cookies, persistent cookies, and third-party cookies.Session cookies store what’s called a session ID, which can be used to assign different requests of your browser to a common session. This allows your device to be recognized when you return to our website. For example, this lets you store certain information you have entered (such as log-in information, language settings) in such a way that you do not have to repeat it constantly. Session cookies are automatically deleted when you log out or close your browser.</p>
    <p>Persistent cookies remain on your device for the time being, so that we can recognize your browser on your next visit and we can, for example, assign your preferred information and settings. Long-term cookies are automatically deleted after a specified period, which may vary depending on the cookie.</p>
    <p>When you visit our website, our partner companies also store third-party cookies on your device. The cookies contain information about how our website is used, e.g. which pages and products were visited. The data is collected in a pseudonymized form by assigning an identification number, which is not combined with any other personal data you may have provided to us.</p>
    <p>You can delete cookies in your browser settings at any time or prevent them from being stored, although the latter may result in a restriction of the functionality of our website for you. In the relevant sections of this Privacy Policy, we explain which technologies that are comparable to cookies are used on our website and how you can object to the use of cookies and other technologies with the individual third-party providers.</p>
    <h3>2.2 Ordering from Binco / User Account</h3>
    <p>a) If you want to order something in our online shop, it is necessary for the conclusion of the contract that you give us the personal data we need to process the order. The mandatory data required to process the contract is marked as such; all other data you provide is voluntary. You can either enter your data only once for the order or use your email address to set up a password-protected user account with us, in which your data can be stored for later purchases until you revoke your consent. You can deactivate or delete the data and the user account at any time via the account.</p>
    <p>To prevent unauthorized access to your personal data by third parties, the order process is encrypted using TLS technology.</p>
    <p>When we process the data provided by you to process your order, this includes, for example, individual customer service. In the course of order processing, we pass on personal data to one of our production companies within the group, to a shipping company commissioned by us and (with the exception of PayPal) to our bank, ADYEN B.V., Simon Carmiggeltstraat 6-50, 1011 DJ Amsterdam, Netherlands (“Adyen”). The payment data is encrypted and transmitted directly to Adyen.</p>
    <p>Payment via PayPal is processed by PayPal, 2211 North First Street San Jose, California 95131 (“PayPal”). For information about data protection at PayPal, please refer to PayPal’s privacy policy: https://www.paypal.com/us/webapps/mpp/ua/privacy-full. In the case of trackable parcels, we also pass on your order and address data to various service providers, depending on your delivery choices, shipping rates, and your chosen delivery destination. The legal bases for the processing of personal data as part of order processing are to perform under a contract and our legitimate interests. Due to commercial and tax regulations, we are obliged to store your order, address and payment data for a period of ten years.</p>
    <p>b) During the order process we also conduct a fraud prevention check via our bank Adyen, which involves using your IP address to carry out a geolocalization and compare your data with previous experience. This may mean that an order cannot be placed with the selected payment method. Our aim in this regard is to prevent any abuse of your chosen payment method by third parties and to protect ourselves from payment defaults. The legal basis for the processing is our legitimate interests.</p>
    <p>Since this involves automated decision-making, you have the right to challenge the decision (in this case the refusal of a certain payment method) and have the decision reviewed by a person. In such cases we ask that you contact us using the contact details mentioned in Section 1. Please note that the payment method may have been rejected due to a typing error and you should, therefore, check what you have entered again during the order process if necessary.</p>
    <p>c) During the ordering process we use Google Maps Autocomplete, a service of Google LLC (“Google”). This allows an address you start typing to be completed automatically, avoiding delivery errors. Google sometimes conducts a geolocalization using your IP address and receives the information that you have retrieved the corresponding subpage of our website. In addition, the data referred to in Section 2.1 is transmitted. This is regardless of whether you have a Google account and are logged in. Once you are logged in to your Google Account, the information will be directly associated with your account. If you do not want this assignment to occur, you must log out before entering your address. Google stores your data as user profiles and uses it (even in the case of users who are not logged in) for the purposes of advertising, market research and/or the needs-oriented design of its own website. You can object to Google creating such user profiles. For more information about the purpose and scope of data processing by Google and about protecting your privacy, please refer to Google’s Privacy Policy: https://policies.google.com/privacy. The binding terms of use for Google Maps/Google Earth can be found here: https://www.google.com/help/terms_maps.html. Third-party provider information: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. The legal basis for the processing is our legitimate interests.</p>
    <p>d) After you place an order, we will process your order and address data to send you a personalized email asking you to rate our products. By obtaining ratings, our aim is to improve our services and adapt them to our customers’ wishes. We use the feedback software of eKomi Ltd, Markgrafenstraße 11, 10969 Berlin, Germany (“eKomi”). For the purpose of sending the feedback email (and in the event that a moderation or conciliation procedure is conducted via eKomi following negative feedback), we pass on your email address, name, order number, product types and a unique ID to eKomi for identification purposes and in order to generate a feedback link.</p>
    <p>The legal basis for the processing is our legitimate interests. If you no longer want your data to be used for this purpose, you can object to this at any time. Just click on the unsubscribe link included with each email or send a message using the contact details provided under Section 1.</p>
    <p>e) We also use Google Customer Reviews, a service of Google Ireland Ltd. (“Google”), through which we receive feedback about us as a seller and about our products. This allows us to improve our services and adapt them to our customers’ wishes. The legal basis is our legitimate interests. After placing an order, you can give Google permission to use your email address to request a review. You can revoke your consent to the use of your data at any time by clicking on the unsubscribe link contained in the emails from Google. For more detailed information about the purpose and scope of data processing by Google and about protecting your privacy, please refer to Google’s Privacy Policy: https://policies.google.com/privacy. Third-party provider information: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p>
    <h3>2.3 Binco Partners: Shop Partners and Marketplace Designers</h3>
    <p>a) If you want to offer designs on our marketplace or operate a shop, it is necessary for the conclusion of a contract with us that you use your email address to open a password-protected user account and store your name and address there. For the payout of earnings, it is necessary that you additionally provide your bank details or your PayPal information as well as information about your tax status. Any other information you may provide to us when using the account is voluntary. You do not have to enter a real name when choosing your username. You can manage and change this information in your account. You can also deactivate or erase it – or the entire user account. If this affects data necessary for the performance of the contract, we may retain that data for a longer period in accordance with commercial and tax regulations (standard period of ten years). We process this data to conduct the contractual relationship that exists with you; the legal bases are to perform under a contract and our legitimate interests. </p>
    <p>b) Within the scope of the contractual relationship, we also process the email address provided by you in order to send you emails at irregular intervals containing information and tips about the Marketplace and your shops (“Partner Newsletter”). We use your name to allow us to personalize these emails. To this end, the data is passed on to the software company Emarsys eMarketing Systems AG, Hans-Fischer-Straße 10, 80339 Munich, Germany (“Emarsys”), which handles the technical side of the mailing on our behalf. You can unsubscribe from the Partner Newsletter at any time by clicking on the unsubscribe link provided in each email, informing us via the contact details specified in Section 1, or changing your newsletter settings in your user account (“Account Settings” – “Newsletter subscriptions”)</p>
    <p>When sending the Partner Newsletter, we use Emarsys to statistically evaluate your user behavior in order to optimize the design. To enable this evaluation, the emails contain what are called web beacons or tracking pixels. These are single-pixel image files that establish a connection to our website und thus permit a log file analysis. The web beacons are linked with the data mentioned in Section 2.1 a and an individual ID. The links contained in the email also contain this ID. For example, we can see if and when an email has been opened and which links have been clicked on. The data is stored on the Emarsys servers for 13 months and collected pseudonymously, meaning the IDs are not linked to other personal data at this point, thus ruling out any possibility of direct personal reference. You can object to the recording of your usage behavior at any time by clicking on the unsubscribe link provided in each email, informing us via the contact options listed in Section 1, or changing the newsletter settings in your user account (“Account settings” – “Newsletter subscriptions”). Recording is not possible if you have disabled the display of images in your email settings. In this case, the newsletter will not be displayed to you in full and you may not be able to use all functions. If you choose to display the images manually, recording will take place as described above. The legal bases for the processing are your consent, to perform under a contract, and our legitimate interests.</p>
    <p>c) If you store your address in your user account, we use Google Maps Autocomplete, a service of Google LLC (“Google”). This allows an address you start typing to be completed automatically. This helps us verify your address, which we do for tax reasons. Google sometimes conducts a geolocalization using your IP address. We also use Google Fonts to enhance the user experience in the Partner section of your account as well as Google Calendar to inform you about Partner-related promotions for customers. Via these services and applications, Google receives the information that you have retrieved the corresponding subpage of our website. In addition, the data referred to in Section 2.1 is transmitted. This is regardless of whether you have a Google account and are logged in. Once you are logged in to your Google Account, the information will be directly associated with your account. If you do not want this assignment to occur, you must log out before entering your address. Google stores your data as user profiles and uses it (even in the case of users who are not logged in) for the purposes of advertising, market research and/or the needs-oriented design of its own website. You can object to Google creating such user profiles. For more detailed information about the purpose and scope of data processing by Google and about protecting your privacy, please refer to Google’s Privacy Policy: https://policies.google.com/privacy. The binding terms of use for Google Maps/Google Earth can be found here: https://www.google.com/help/terms_maps.html. Third-party provider information: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA. The legal basis for the processing is our legitimate interests.</p>
    <h3>2.4 Communication with Binco</h3>
    <h4>a) Establishing contact</h4>
    <p>If you contact us via a contact form, letter, fax, email, social media or telephone, we process the data provided by you for the purpose of processing your inquiry and for advertising purposes. We use the software of Sematell GmbH, Neugrabenweg 1, 66123 Saarbrücken, Germany, to coordinate and process emails, which means that Sematell GmbH gains access to the data. We use the management software of Hootsuite Media, Inc, 5 East 8th Avenue, Vancouver, BC, Canada to coordinate and process enquiries via our social media channels Twitter, Facebook and Instagram. The legal basis for the processing is our legitimate interests. If the aim of establishing contact is to conclude a contract, then an additional legal basis is to perform under a contract.</p>
    <h4>b) Blog</h4>
    <p>In our blog, where we publish various articles on topics related to our activities, you can post public comments. Your comment will be published along with your chosen username. We recommend using a pseudonym instead of your real name. It is necessary to provide a username and email address, while all other information is voluntary. The necessary information is processed to run the blog. We need your email address to contact you if a third party should complain that your comment is unlawful. We reserve the right to delete comments if third parties complain that they are unlawful. The legal basis for the processing is our legitimate interests.</p>
    <h4>c) Forum</h4>
    <p>With the exception of a few sections, our Forum can be read without the need to register. If you wish to actively participate in the Forum under your chosen username, you must log in using your Binco user account access data. To open a Binco user account, only your email address and a password are required. We process your activities (public posts, private messages, likes, profile information, activity logs) and your IP address in order to operate the Forum. The legal basis is our legitimate interests. If you deactivate or delete your user account, your public posts will continue to be visible. If you would like your public posts to be deleted, please contact us using the contact details provided in Section 1. When writing a comment and in the Forum settings (under “Preferences” – “Emails” and “Notifications”), you can specify in which cases and to what extent you would like to be notified by email about new activities in the Forum. You can unsubscribe again at any time, either in the Forum settings or by clicking on the unsubscribe link contained in the respective notification email.</p>
    <h3>2.5 Processing of data for web analytics</h3>
    <h4>a) Google Analytics</h4>
    <p>Our website uses Google Analytics, a web analytics service provided by Google Ireland Ltd. (“Google”). Google uses cookies (see Section 2.1 b), which enable an analysis of your use of our website. The information generated by the cookie about usage is usually transferred to a Google server in the USA and stored there. However, due to the activation of IP anonymization on our website, where applicable, your IP address will first be shortened by Google within the Member States of the European Union or in other states party to the Agreement on the European Economic Area. Only in exceptional cases will the full IP address be transmitted to a Google server in the USA and shortened there. On our behalf, Google will use this information to evaluate your use of the website, to compile reports on website activity and to provide us with other services relating to website and internet use.</p>
    <p>You can prevent the storage of cookies by selecting the appropriate settings in your browser software; however, please note that if you do this you may not be able to use the full functionality of our website. You can also prevent the data generated by the cookie and relating to your use of the website (including your IP address) from being recorded and processed by Google by downloading and installing the browser plug-in available under the following link: https://tools.google.com/dlpage/gaoptout/. Specifically in the case of mobile devices, you can prevent Google Analytics from recording data by clicking here: Disable Google Analytics. This will place an opt-out cookie which prevents recording when you visit our website in future. Please note that if you delete all cookies on your device, this opt-out cookie will also be deleted; in this case, if you still wish to object then you must place the cookie again using the above button. The opt-out cookie is set per top-level domain, per browser and per device and only prevents the recording of data for this website.</p>
    <p>This website uses Google Analytics with the “_anonymizeIp()” extension. Consequently, IP addresses are further processed in shortened form, so that any personal association with the data subject can be ruled out. As far as the data collected about you relates to you personally, that association is therefore ruled out immediately and the personal data thus erased without delay.</p>
    <h4>b) Adobe Analytics</h4>
    <p>To allow us to analyze and regularly improve the use of our website, our website also uses the Adobe Analytics web analytics service. The statistics this yields allow us to improve our website and make it more interesting for you as a user. The legal bases for our use of Adobe Analytics are your consent and our legitimate interests.</p>
    <p>The analysis involves storing cookies (see Section 2.1 b) on your device. The information collected in this way is stored on servers, including in the USA. We would like to point out that if you prevent the storage of cookies, you may not be able to use this website in its entirety. You can adjust your browser settings to prevent the storage of cookies. You can also prevent Adobe Analytics from recording your data on this website by clicking here: Disable Adobe Analytics. This will place an opt-out cookie which prevents recording when you visit our website in future. Please note that if you delete all cookies on your device, this opt-out cookie will also be deleted; in this case, if you still wish to object then you must place the cookie again using the above button. The opt-out cookie is set per top-level domain, per browser and per device and only prevents the recording of data for this website. How to prevent the recording of your data on other websites is explained on the respective sites and at https://www.adobe.com/privacy/opt-out.html.</p>
    <h4>c) Hotjar</h4>
    <p>Our website also uses the web analytics service Hotjar from Hotjar Ltd. This service allows us to track movements on our website (so-called heat maps). These make it possible to see how much time you spend on which pages, how far you scroll, the movement of your mouse and how often you click on certain links and buttons. Your keystroke data, i.e. your entries in input fields, are not recorded. Hotjar uses cookies (see point 2.1 b) to collect this information about your behavior, as well as the following information about your device: IP address of the device (only collected and stored in an abbreviated, anonymized form), screen size, device type (unique device identifiers), browser used, geographic location (country only) and language preferred when viewing the online offer. Hotjar Ltd. stores the information on servers in Ireland for 365 days, after which the data is deleted. Neither Hotjar Ltd. nor we will merge or associate the information with any other data about you, and it will not be used to identify individual users. The data collected by Hotjar Ltd. is only used for our internal evaluation of the user behavior when interacting with our online offer. It is used to improve aspects of user-friendliness of our website. To the extent that you have given us your consent, the legal basis for processing is your consent, and otherwise the legal basis is our legitimate interests.</p>
    <p>You can prevent the storage of cookies by selecting the appropriate settings in your browser software; however, please note that if you do this you may not be able to use the full functionality of our website. You can also prevent Hotjar from recording your data on this website by clicking here: Disable Hotjar. This will place an opt-out cookie which prevents recording when you visit our website in future. Please note that if you delete all cookies on your device, this opt-out cookie will also be deleted; in this case, if you still wish to object then you must place the cookie again using the above button. The opt-out cookie is set per top-level domain, per browser and per device, and only prevents the recording of data for this website. How to prevent collection on other websites is explained on the respective site and here: https://www.hotjar.com/privacy/do-not-track/.</p>
    <h4>d) Web analytics by Binco’s Shop Partners</h4>
    <p>Our partners can also use the Google Analytics web analytics service (see Section 2.5 a) in their Binco shops themselves, as a rule to analyze use of the shop and improve their offer in the shop. In this case, they determine the purposes and means of processing personal data. The name and contact details of our partners are stored in the legal information section of the respective shop.</p>
    <h3>3. What are my rights?</h3>
    <p>If you have given your consent to the processing of your data, you can revoke this consent with future effect at any time. This does not affect the lawfulness of processing carried out on the basis of the consent before you revoke your consent.</p>
    <p>If we base the processing of your personal data on our legitimate interests, you are entitled to object to the processing. This is the case if the processing is not necessary in particular for the performance of a contract with you, which was described by us in each case with the description of the individual functions. When exercising such a right of objection, we ask that you explain the reasons why we should not process your personal data as carried out by us. In the event that your objection is justified, we will examine the situation and either stop or adjust the data processing or point out to you the compelling legitimate reasons on the basis of which we will continue processing.</p>
    <p>However, you can of course object to the processing of your personal data for advertising or web analytics purposes at any time without giving reasons. As described in the relevant sections, we sometimes use external service providers to process your data. These have been carefully selected and commissioned by us, are bound by our instructions and are regularly checked.</p>
    <p>The personal data processed by us is generally erased or blocked as soon as the purpose of storage ceases to apply. Data may be stored for a longer period if this has been provided for by laws or other rules to which we as the controller are subject. The data will also be blocked or erased once a storage period prescribed by the aforementioned standards expires, unless there is a need for further storage of the data for the conclusion or performance of a contract. Further processing operations may be required for contests and other promotional campaigns. In such cases we will inform you in the context of the respective promotional campaign.</p>
    <h3>4. We Will Share Your Information with Third Parties in Specific Circumstances</h3>
    <h4>a) Legal Compliance and Safety</h4>
    <p>There are a few times when we must share your information either to protect our rights or to obey the law. We will share your personal information when we believe in good faith that:</p>
    <ul>
      <li>a subpoena or warrant is duly issued, or we receive any other legitimate government agency request to produce information;</li>
      <li>we need to share the information in order to enforce or protect our own rights, for example, to respond to and resolve third-party claims or complaints, or with respect to contracts with our users and third parties;</li>
      <li>we need to address a security or technical issue within our website;</li>
      <li>sharing the information is necessary to prevent harm to others or others’ property, especially in an emergency situation;</li>
    </ul>
      <h4>b) Corporate Change in Control Events</h4>
      <p>If we sell all or part of our business, or make a sale or transfer of assets, or are otherwise involved in a similar event, we may transfer your information as part of that transaction.</p>
      <h3>5. Is My Information Secure?</h3>
      <p>We use reasonable measures to secure our website and any private information you submit to us against loss, tampering, unauthorized access, and other malicious acts. For example, we use SSL connections when possible to protect your data while it is in transit (for example login data and customer orders). However, no data transmission over the Internet is completely secure, so we cannot completely guarantee the security of any data. You use our services at your own risk, and are responsible for taking reasonable measures to secure your password, information, and account.</p>
      <h3>6. Do-Not-Track (“DNT”) Requests</h3>
      <p>Due to lack of technical standards across browsers, we do not respond to DNT signals.</p>
      <h3>7. Privacy Statement for California Residents</h3>
      <p>a) The California Consumer Privacy Act </p>
      <p>This privacy statement supplements the information contained above and applies solely to “consumers” (as defined in the California Consumer Privacy Act (“CCPA”)). All terms defined in the CCPA have the same meaning when used in this section. For example, “consumer” means a California resident, and “personal information” means “information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or device” but does not include “publicly available,” “de-identified,” or “aggregated” information. In this section, “you” refers only to California residents.</p>
      <p>b) Consumer Rights </p>
      <p>Consumers have the following rights under the CCPA: </p>
      <ul>
        <li>The right to request that a business disclose the categories of personal information it collects, uses, discloses, and sells about the consumer.</li>
        <li>The right to request the deletion of personal information collected or maintained by a business.</li>
        <li>The right to request that a business disclose the categories of sources for personal information collection. </li>
        <li>The right to request that a business disclose the business or commercial purpose for collecting personal information</li>
        <li>The right to request that a business disclose the categories of third parties with whom the business shares personal information.</li>
        <li>The right to request that a business disclose to the consumer the specific pieces of personal information it collects, uses, discloses, and sells about that consumer (or any member of the consumer’s household).</li>
        <li>If a business discloses personal information for a business purpose, the right to request that a business disclose the categories of personal information that the business disclosed about the consumer for a business purpose and the categories of third parties to whom personal information was disclosed for a business purpose.</li>
        <li>If the business sells personal information for monetary or other valuable consideration, the right to opt-out of the sale of their personal information by a business. This is the so-called “right to opt-out.”</li>
        <li>The right not to receive discriminatory treatment by a business for the exercise of the privacy rights conferred by the CCPA.</li>
        <li>The right to make requests under the CCPA by using an authorized agent designated by the consumer.</li>
      </ul>
      <p>d) Other Information Sale Disclosures </p>
      <p>Do Not Sell My Personal Information. Click the link to the left to learn how to opt out of the “sale” of your personal information as defined in the CCPA. We have no actual knowledge that the personal information we sell belongs to minors under 16 years of age.  </p>
      <p>e) Notice of Financial Incentive </p>
      <p>Binco has a customer newsletter with advertisements and exclusive coupons. To subscribe, just submit your email address in the box at Binco.com. Unsubscribe anytime at no cost by clicking the unsubscribe link in each newsletter email. The value of each submitted email address is approximately $2.59 USD over the course of twelve months. Binco arrived at this value by comparing the spending habits of customers who have subscribed to the newsletter with those who have not. </p>
      <h3>8. Children’s Online Privacy Protection</h3>
      <p>Our website is not intended or directed at individuals under the age of 13. We do not knowingly collect or keep any information of children under the age of 13. If we discover it, we will delete it as soon as possible.</p>
      <h3>9. Effective Date and Changes</h3>
      <p>This policy is effective as of July 1, 2020. Any material changes to this Privacy Policy will be announced to you on the website and/or via email.</p>
      <p>Thank you for reading this privacy policy in its entirety!</p>
    </div>
    </>
    )
  }
}
